### ISSUE TITLE
raspberry pi version

### ISSUE THREAD

**Issue by therock** [firsttris/tvheadend-sundtek-docker#1]
Hi would it be possible for you to build a version and publish it on dockerhub for a raspberry pi?

**Comment by firsttris** [comment]
there is already automated build in dockerhub:
https://hub.docker.com/r/tristanteu/tvheadend-sundtek-docker/
can you verify & report back if its working on the raspberry?

**Comment by therock** [comment]
its not, i tried it first i think its because the base layer is based on debian non arm

**Comment by firsttris** [comment]
currently i have no time to create such an raspberry pi image..i think its probably not very interesing because the raspberry has to low resource to be a good tvheadend server. if your still interested im happy to about any pullrequests. i switched to a SAT>IP Server XORO 8100 130€, 8 Tuners and no driver hassle with tvheadend at all.
